In [1]:
%run setup_workspace.py

In [2]:
scan_session(
    session_path=r'\\Synology\Data\2025\SC_5732',
    catalog_path=r"Experimet_Catalog.csv"
)

Scanning SAXS: 100%|█████████████████████████████████████████████████████████████████| 204/204 [00:04<00:00, 42.52it/s]
Scanning WAXS: 100%|█████████████████████████████████████████████████████████████████| 204/204 [00:04<00:00, 48.31it/s]

Catalog updated: 372 experiments added to SC_5732
Total entries in catalog: 94353

In [12]:
path = r'C:\Users\LabPCA\Desktop\X_Ray_Scattering_Analysis/Experimet_Catalog.csv'
df = pd.read_csv(path)
df.head()

,session,title,keys,file_path,file_type
0,BM26 SC5736,Capillary_2mm_water,NaN,\\Synology\Data\2024\BM26 SC5736\Capillary_2mm...,edf/dat
1,BM26 SC5736,Capillary_2mm_water,NaN,\\Synology\Data\2024\BM26 SC5736\Capillary_2mm...,edf/dat
2,BM26 SC5736,PEG_PLA_11_pristine,NaN,\\Synology\Data\2024\BM26 SC5736\PEG_PLA_11_pr...,edf/dat
3,BM26 SC5736,PEG_PLA_11_pristine,NaN,\\Synology\Data\2024\BM26 SC5736\PEG_PLA_11_pr...,edf/dat
4,BM26 SC5736,PEG_PLA_8_bis,NaN,\\Synology\Data\2024\BM26 SC5736\PEG_PLA_8_bis...,edf/dat

In [26]:
filtered_df = df[df['title'].str.contains('Oh', case=False, na=False) 
                 # & df['title'].str.contains('heat', case=False, na=False)
    ]

filtered_df

,session,title,keys,file_path,file_type
204,BM26_Feb2024,NOHPDMS_100perc_stretcher,NaN,\\Synology\Data\2024\BM26_Feb2024\NOHPDMS_100p...,edf/dat
205,BM26_Feb2024,NOHPDMS_100perc_stretcher,NaN,\\Synology\Data\2024\BM26_Feb2024\NOHPDMS_100p...,edf/dat
206,BM26_Feb2024,NOHPDMS_100perc_stretcher_repeat,NaN,\\Synology\Data\2024\BM26_Feb2024\NOHPDMS_100p...,edf/dat
207,BM26_Feb2024,NOHPDMS_100perc_stretcher_repeat,NaN,\\Synology\Data\2024\BM26_Feb2024\NOHPDMS_100p...,edf/dat
208,BM26_Feb2024,NOHPDMS_100pers,NaN,\\Synology\Data\2024\BM26_Feb2024\NOHPDMS_100p...,edf/dat
...,...,...,...,...,...
90369,sc5665,NOH_NG_6_Melt_20ms_1_1m,NaN,\\Synology\Data\2025\sc5665\id02\20250404\PROC...,unknown
90370,sc5665,NOH_NG_6_Melt_20ms_1_1m,NaN,\\Synology\Data\2025\sc5665\id02\20250404\PROC...,unknown
90371,sc5665,NOH_NG_6_Melt_20ms_1_1m,NaN,\\Synology\Data\2025\sc5665\id02\20250404\PROC...,unknown
90372,sc5665,NOH_NG_6_Melt_20ms_1_1m,NaN,\\Synology\Data\2025\sc5665\id02\20250404\PROC...,unknown
90373,sc5665,NOH_NG_6_Melt_20ms_1_1m,NaN,\\Synology\Data\2025\sc5665\id02\20250404\PROC...,unknown

In [27]:
for title in filtered_df['title']:
    print(title)

NOHPDMS_100perc_stretcher
NOHPDMS_100perc_stretcher
NOHPDMS_100perc_stretcher_repeat
NOHPDMS_100perc_stretcher_repeat
NOHPDMS_100pers
NOHPDMS_100pers
NOHPDMS_90perc_stretcher
NOHPDMS_90perc_stretcher
NOHPDMS_90pers
NOHPDMS_90pers
NOH_0perc_hexane_Solution_1_25perc
NOH_0perc_hexane_Solution_1_25perc
NOH_0perc_hexane_Solution_2_5perc
NOH_0perc_hexane_Solution_2_5perc
NOH_0perc_hexane_second_Solution_0_6perc
NOH_0perc_hexane_second_Solution_0_6perc
NOH_100perc_hexane_Hexane_pure
NOH_100perc_hexane_Hexane_pure
NOH_100perc_hexane_Solution_1_25perc
NOH_100perc_hexane_Solution_1_25perc
NOH_100perc_hexane_Solution_2_5perc
NOH_100perc_hexane_Solution_2_5perc
NOH_100perc_hexane_second_Solution_0_6perc
NOH_100perc_hexane_second_Solution_0_6perc
NOH_100perc_melt_static_1_4m
NOH_100perc_melt_static_1_4m
NOH_50perc_melt_static_1_4m
NOH_50perc_melt_static_1_4m
NOH_80perc_melt_static_1_4m
NOH_80perc_melt_static_1_4m
NOH_Zero_perc_melt_static_1_4m
NOH_Zero_perc_melt_static_1_4m
NOH_PDMS_20perc_3_5mm_initial
NOH_PDMS_20perc_3_5mm_initial
NOH_PDMS_20perc_3_5mm_initial
NOH_PDMS_20perc_3_5mm_initial
NOH_PDMS_20perc_3mm_initial
NOH_PDMS_20perc_3mm_initial
NOH_PDMS_20perc_3mm_initial
NOH_PDMS_20perc_3mm_initial
NOH_PDMS_20perc_3mm_initial_bis
NOH_PDMS_20perc_3mm_initial_bis
NOH_PDMS_20perc_3mm_initial_bis
NOH_PDMS_20perc_3mm_initial_bis
NOH_PDMS_20perc_4_5mm_bis
NOH_PDMS_20perc_4_5mm_bis
NOH_PDMS_20perc_4_5mm_bis
NOH_PDMS_20perc_4_5mm_bis
NOH_PDMS_20perc_5_5mm_bis
NOH_PDMS_20perc_5_5mm_bis
NOH_PDMS_20perc_5_5mm_bis
NOH_PDMS_20perc_5_5mm_bis
NOH_PDMS_20perc_5mm_bis
NOH_PDMS_20perc_5mm_bis
NOH_PDMS_20perc_5mm_bis
NOH_PDMS_20perc_5mm_bis
NOH_PDMS_50perc_3_5mm
NOH_PDMS_50perc_3_5mm
NOH_PDMS_50perc_3_5mm
NOH_PDMS_50perc_3_5mm
NOH_PDMS_50perc_3mm_initial
NOH_PDMS_50perc_3mm_initial
NOH_PDMS_50perc_3mm_initial
NOH_PDMS_50perc_3mm_initial
NOH_PDMS_50perc_4_5mm
NOH_PDMS_50perc_4_5mm
NOH_PDMS_50perc_4_5mm
NOH_PDMS_50perc_4_5mm
NOH_PDMS_50perc_4mm
NOH_PDMS_50perc_4mm
NOH_PDMS_50perc_4mm
NOH_PDMS_50perc_4mm
NOH_PDMS_50perc_5_5mm
NOH_PDMS_50perc_5_5mm
NOH_PDMS_50perc_5_5mm
NOH_PDMS_50perc_5_5mm
NOH_PDMS_50perc_5mm
NOH_PDMS_50perc_5mm
NOH_PDMS_50perc_5mm
NOH_PDMS_50perc_5mm
NOH_PDMS_50perc_6_5mm
NOH_PDMS_50perc_6_5mm
NOH_PDMS_50perc_6_5mm
NOH_PDMS_50perc_6_5mm
NOH_PDMS_50perc_6mm
NOH_PDMS_50perc_6mm
NOH_PDMS_50perc_6mm
NOH_PDMS_50perc_6mm
NOH_PDMS_50perc_7_5mm
NOH_PDMS_50perc_7_5mm
NOH_PDMS_50perc_7_5mm
NOH_PDMS_50perc_7_5mm
NOH_PDMS_50perc_7mm
NOH_PDMS_50perc_7mm
NOH_PDMS_50perc_7mm
NOH_PDMS_50perc_7mm
NOH_PDMS_50perc_8_25mm
NOH_PDMS_50perc_8_25mm
NOH_PDMS_50perc_8_25mm
NOH_PDMS_50perc_8_25mm
NOH_PDMS_50perc_8mm
NOH_PDMS_50perc_8mm
NOH_PDMS_50perc_8mm
NOH_PDMS_50perc_8mm
NOH_PDMS_80perc_2_25mm
NOH_PDMS_80perc_2_25mm
NOH_PDMS_80perc_2_25mm
NOH_PDMS_80perc_2_25mm
NOH_PDMS_80perc_2_5mm
NOH_PDMS_80perc_2_5mm
NOH_PDMS_80perc_2_5mm
NOH_PDMS_80perc_2_5mm
NOH_PDMS_80perc_2_75mm
NOH_PDMS_80perc_2_75mm
NOH_PDMS_80perc_2_75mm
NOH_PDMS_80perc_2_75mm
NOH_PDMS_80perc_2mm_initial
NOH_PDMS_80perc_2mm_initial
NOH_PDMS_80perc_2mm_initial
NOH_PDMS_80perc_2mm_initial
NOH_PDMS_80perc_3_25mm
NOH_PDMS_80perc_3_25mm
NOH_PDMS_80perc_3_25mm
NOH_PDMS_80perc_3_25mm
NOH_PDMS_80perc_3_5mm
NOH_PDMS_80perc_3_5mm
NOH_PDMS_80perc_3_5mm
NOH_PDMS_80perc_3_5mm
NOH_PDMS_80perc_3_75mm
NOH_PDMS_80perc_3_75mm
NOH_PDMS_80perc_3_75mm
NOH_PDMS_80perc_3_75mm
NOH_PDMS_80perc_3mm
NOH_PDMS_80perc_3mm
NOH_PDMS_80perc_3mm
NOH_PDMS_80perc_3mm
NOH_PDMS_80perc_4_25mm
NOH_PDMS_80perc_4_25mm
NOH_PDMS_80perc_4_25mm
NOH_PDMS_80perc_4_25mm
NOH_PDMS_80perc_4_5mm
NOH_PDMS_80perc_4_5mm
NOH_PDMS_80perc_4_5mm
NOH_PDMS_80perc_4_5mm
NOH_PDMS_80perc_4_75mm
NOH_PDMS_80perc_4_75mm
NOH_PDMS_80perc_4_75mm
NOH_PDMS_80perc_4_75mm
NOH_PDMS_80perc_4mm
NOH_PDMS_80perc_4mm
NOH_PDMS_80perc_4mm
NOH_PDMS_80perc_4mm
NOH_PDMS_80perc_5_25mm
NOH_PDMS_80perc_5_25mm
NOH_PDMS_80perc_5_25mm
NOH_PDMS_80perc_5_25mm
NOH_PDMS_80perc_5_5mm
NOH_PDMS_80perc_5_5mm
NOH_PDMS_80perc_5_5mm
NOH_PDMS_80perc_5_5mm
NOH_PDMS_80perc_5_75mm
NOH_PDMS_80perc_5_75mm
NOH_PDMS_80perc_5_75mm
NOH_PDMS_80perc_5_75mm
NOH_PDMS_80perc_5mm
NOH_PDMS_80perc_5mm
NOH_PDMS_80perc_5mm
NOH_PDMS_80perc_5mm
NOH_PDMS_80perc_6mm
NOH_PDMS_80perc_6mm
NOH_PDMS_80perc_6mm
NOH_PDMS_80perc_6mm
OHPDMS_linear_100perc_statics
OHPDMS_linear_100perc_statics
OHPDMS_linear_100perc_statics_realone
OHPDMS_linear_100perc_statics_realone
OHPDMS_linear_50perc_statics
OHPDMS_linear_50perc_statics
OHPDMS_linear_80perc_statics
OHPDMS_linear_80perc_statics
OH_PDMS_100perc_crosslinked_fromlasttime
OH_PDMS_100perc_crosslinked_fromlasttime
OH_PDMS_100perc_in_toluene_10perc
OH_PDMS_100perc_in_toluene_10perc
OH_PDMS_100perc_in_toluene_30perc
OH_PDMS_100perc_in_toluene_30perc
OH_PDMS_100perc_in_toluene_5perc
OH_PDMS_100perc_in_toluene_5perc
OH_PDMS_100perc_uncrossl_sherared
OH_PDMS_100perc_uncrossl_sherared
OH_PDMS_10perc_Uncrossl_after_3_5hrs_RT
OH_PDMS_10perc_Uncrossl_after_3_5hrs_RT
OH_PDMS_10perc_Uncrossl_after_5hrs_RT
OH_PDMS_10perc_Uncrossl_after_5hrs_RT
OH_PDMS_50perc_Uncrossl_WithCover_Heat
OH_PDMS_50perc_Uncrossl_WithCover_Heat
OH_PDMS_50perc_as_received
OH_PDMS_50perc_as_received
OH_PDMS_50perc_uncrossl_afterheat_to_100C
OH_PDMS_50perc_uncrossl_afterheat_to_100C
OH_PDMS_80perc_as_received
OH_PDMS_80perc_as_received
OH_PDMS_80perc_uncrossl_afterheat_to_100C
OH_PDMS_80perc_uncrossl_afterheat_to_100C
OH_PDMS_90perc_crosslinked_fromlasttime
OH_PDMS_90perc_crosslinked_fromlasttime
OH_PDMS_ThinFilm_Rubbed_paral
OH_PDMS_ThinFilm_Rubbed_paral
OH_PDMS_ThinFilm_Rubbed_perpend
OH_PDMS_ThinFilm_Rubbed_perpend
OH_PDMS_as_received
OH_PDMS_as_received
OH_PDMS_crosslink_heating
OH_PDMS_crosslink_heating
BCPs_3350_3_cyclohexane_ascast
BCPs_3350_3_cyclohexane_ascast
Chiral_PDMS_OH_Chiral_PDMS_OH_above_toluene_Capil
Chiral_PDMS_OH_Chiral_PDMS_OH_above_toluene_Capil
Chiral_PDMS_OH_Chiral_PDMS_OH_above_toluene_Capil_after_Night
Chiral_PDMS_OH_Chiral_PDMS_OH_above_toluene_Capil_after_Night
EM_NOHPDMS_90perc_melt_1m_20C
EM_NOHPDMS_90perc_melt_1m_20C
EM_NOHPDMS_90perc_melt_1m_20C
EM_NOHPDMS_90perc_melt_1m_30C
EM_NOHPDMS_90perc_melt_1m_30C
EM_NOHPDMS_90perc_melt_1m_30C
EM_NOHPDMS_90perc_melt_1m_40C
EM_NOHPDMS_90perc_melt_1m_40C
EM_NOHPDMS_90perc_melt_1m_40C
EM_NOHPDMS_90perc_melt_1m_40C_bis
EM_NOHPDMS_90perc_melt_1m_40C_bis
EM_NOHPDMS_90perc_melt_1m_40C_bis
EM_NOHPDMS_90perc_melt_1m_50
EM_NOHPDMS_90perc_melt_1m_50
EM_NOHPDMS_90perc_melt_1m_50
EM_NOHPDMS_90perc_melt_1m_75
EM_NOHPDMS_90perc_melt_1m_75
EM_NOHPDMS_90perc_melt_1m_75
EM_NOHPDMS_90perc_melt_1m_sheared
EM_NOHPDMS_90perc_melt_1m_sheared
EM_NOHPDMS_90perc_melt_1m_sheared
EM_NOHPDMS_90perc_melt_1m_sheared_4th
EM_NOHPDMS_90perc_melt_1m_sheared_4th
EM_NOHPDMS_90perc_melt_1m_sheared_4th
EM_NOHPDMS_90perc_melt_1m_sheared_5th
EM_NOHPDMS_90perc_melt_1m_sheared_5th
EM_NOHPDMS_90perc_melt_1m_sheared_5th
EM_NOHPDMS_90perc_melt_1m_sheared_6th
EM_NOHPDMS_90perc_melt_1m_sheared_6th
EM_NOHPDMS_90perc_melt_1m_sheared_6th
EM_NOHPDMS_90perc_melt_1m_sheared_bis
EM_NOHPDMS_90perc_melt_1m_sheared_bis
EM_NOHPDMS_90perc_melt_1m_sheared_bis
EM_NOHPDMS_90perc_melt_1m_sheared_tris
EM_NOHPDMS_90perc_melt_1m_sheared_tris
EM_NOHPDMS_90perc_melt_1m_sheared_tris
EM_NOH_ng_2_elastomer_13m_1s
EM_NOH_ng_2_elastomer_13m_1s
EM_NOH_ng_2_elastomer_13m_1s
EM_NOH_ng_2_elastomer_13m_1s_30C
EM_NOH_ng_2_elastomer_13m_1s_30C
EM_NOH_ng_2_elastomer_13m_1s_30C
EM_NOH_ng_2_elastomer_13m_1s_40C
EM_NOH_ng_2_elastomer_13m_1s_40C
EM_NOH_ng_2_elastomer_13m_1s_40C
EM_NOH_ng_2_elastomer_13m_1s_50C
EM_NOH_ng_2_elastomer_13m_1s_50C
EM_NOH_ng_2_elastomer_13m_1s_50C
EM_NOH_ng_2_elastomer_13m_1s_75C
EM_NOH_ng_2_elastomer_13m_1s_75C
EM_NOH_ng_2_elastomer_13m_1s_75C
EM_NOH_ng_2_elastomer_13m_1s_75C_bis
EM_NOH_ng_2_elastomer_13m_1s_75C_bis
EM_NOH_ng_2_elastomer_13m_1s_75C_bis
EM_NOH_ng_2_elastomer_1m_1s
EM_NOH_ng_2_elastomer_1m_1s
EM_NOH_ng_2_elastomer_1m_1s
EM_NOH_ng_2_elastomer_1m_1s_75C
EM_NOH_ng_2_elastomer_1m_1s_75C
EM_NOH_ng_2_elastomer_1m_1s_75C
EM_ng_2_NOH_elastomer_1_7m_20C
EM_ng_2_NOH_elastomer_1_7m_20C
EM_ng_2_NOH_elastomer_1_7m_20C
EM_ng_2_NOH_elastomer_1m_20C
EM_ng_2_NOH_elastomer_1m_20C
EM_ng_2_NOH_elastomer_1m_20C
EM_ng_2_NOH_elastomer_1m_30C
EM_ng_2_NOH_elastomer_1m_30C
EM_ng_2_NOH_elastomer_1m_30C
EM_ng_2_NOH_elastomer_1m_40C
EM_ng_2_NOH_elastomer_1m_40C
EM_ng_2_NOH_elastomer_1m_40C
EM_ng_2_NOH_elastomer_1m_50C
EM_ng_2_NOH_elastomer_1m_50C
EM_ng_2_NOH_elastomer_1m_50C
EM_ng_2_NOH_elastomer_1m_75C
EM_ng_2_NOH_elastomer_1m_75C
EM_ng_2_NOH_elastomer_1m_75C
EM_ng_4_NOH_elastomer_1m_20C
EM_ng_4_NOH_elastomer_1m_20C
EM_ng_4_NOH_elastomer_1m_20C
EM_ng_4_NOH_elastomer_1m_30C
EM_ng_4_NOH_elastomer_1m_30C
EM_ng_4_NOH_elastomer_1m_30C
EM_ng_4_NOH_elastomer_1m_40C
EM_ng_4_NOH_elastomer_1m_40C
EM_ng_4_NOH_elastomer_1m_40C
EM_ng_4_NOH_elastomer_1m_50C
EM_ng_4_NOH_elastomer_1m_50C
EM_ng_4_NOH_elastomer_1m_50C
EM_ng_4_NOH_elastomer_1m_75C
EM_ng_4_NOH_elastomer_1m_75C
EM_ng_4_NOH_elastomer_1m_75C
NOH_20perc_small_vial_melt_1m_30C
NOH_20perc_small_vial_melt_1m_30C
NOH_20perc_small_vial_melt_1m_30C
NOH_20perc_small_vial_melt_1m_30C_bis
NOH_20perc_small_vial_melt_1m_30C_bis
NOH_20perc_small_vial_melt_1m_30C_bis
NOH_20perc_small_vial_melt_1m_40C
NOH_20perc_small_vial_melt_1m_40C
NOH_20perc_small_vial_melt_1m_40C
NOH_20perc_small_vial_melt_1m_40C_bis
NOH_20perc_small_vial_melt_1m_40C_bis
NOH_20perc_small_vial_melt_1m_40C_bis
NOH_20perc_small_vial_melt_1m_50C
NOH_20perc_small_vial_melt_1m_50C
NOH_20perc_small_vial_melt_1m_50C
NOH_20perc_small_vial_melt_1m_50C_bis
NOH_20perc_small_vial_melt_1m_50C_bis
NOH_20perc_small_vial_melt_1m_50C_bis
NOH_20perc_small_vial_melt_1m_75C
NOH_20perc_small_vial_melt_1m_75C
NOH_20perc_small_vial_melt_1m_75C
NOH_20perc_small_vial_melt_1m_75C_bis
NOH_20perc_small_vial_melt_1m_75C_bis
NOH_20perc_small_vial_melt_1m_75C_bis
NOH_50pc_0p3125perc_2mm_Capill_100ms_13m
NOH_50pc_0p3125perc_2mm_Capill_100ms_13m
NOH_50pc_0p3125perc_2mm_Capill_100ms_13m
NOH_50pc_0p3125perc_2mm_Capill_100ms_13m
NOH_50pc_0p3125perc_2mm_Capill_100ms_13m
NOH_50pc_0p3125perc_2mm_Capill_100ms_13m
NOH_50pc_0p3125perc_2mm_Capill_100ms_1_1m
NOH_50pc_0p3125perc_2mm_Capill_100ms_1_1m
NOH_50pc_0p3125perc_2mm_Capill_100ms_1_1m
NOH_50pc_0p3125perc_2mm_Capill_100ms_1_1m
NOH_50pc_0p3125perc_2mm_Capill_100ms_1_1m
NOH_50pc_0p3125perc_2mm_Capill_100ms_1_1m
NOH_50pc_0p3125perc_Capill_2mm_50ms_13m
NOH_50pc_0p3125perc_Capill_2mm_50ms_13m
NOH_50pc_0p3125perc_Capill_2mm_50ms_13m
NOH_50pc_0p3125perc_Capill_2mm_50ms_13m
NOH_50pc_0p3125perc_Capill_2mm_50ms_13m
NOH_50pc_0p3125perc_Capill_2mm_50ms_13m
NOH_50pc_0p3125perc_Capill_2mm_50ms_1_1m
NOH_50pc_0p3125perc_Capill_2mm_50ms_1_1m
NOH_50pc_0p3125perc_Capill_2mm_50ms_1_1m
NOH_50pc_0p3125perc_Capill_2mm_50ms_1_1m
NOH_50pc_0p3125perc_Capill_2mm_50ms_1_1m
NOH_50pc_0p3125perc_Capill_2mm_50ms_1_1m
NOH_50pc_0p625perc_2mm_Capill_100ms_13m
NOH_50pc_0p625perc_2mm_Capill_100ms_13m
NOH_50pc_0p625perc_2mm_Capill_100ms_13m
NOH_50pc_0p625perc_2mm_Capill_100ms_13m
NOH_50pc_0p625perc_2mm_Capill_100ms_13m
NOH_50pc_0p625perc_2mm_Capill_100ms_13m
NOH_50pc_0p625perc_2mm_Capill_100ms_1p1m
NOH_50pc_0p625perc_2mm_Capill_100ms_1p1m
NOH_50pc_0p625perc_2mm_Capill_100ms_1p1m
NOH_50pc_0p625perc_2mm_Capill_100ms_1p1m
NOH_50pc_0p625perc_2mm_Capill_100ms_1p1m
NOH_50pc_0p625perc_2mm_Capill_100ms_1p1m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_13m
NOH_50pc_0p625perc_Capill_2mm_50ms_1p1m
NOH_50pc_0p625perc_Capill_2mm_50ms_1p1m
NOH_50pc_0p625perc_Capill_2mm_50ms_1p1m
NOH_50pc_0p625perc_Capill_2mm_50ms_1p1m
NOH_50pc_0p625perc_Capill_2mm_50ms_1p1m
NOH_50pc_0p625perc_Capill_2mm_50ms_1p1m
NOH_50pc_1p25perc_2mm_Capill_100ms_13m
NOH_50pc_1p25perc_2mm_Capill_100ms_13m
NOH_50pc_1p25perc_2mm_Capill_100ms_13m
NOH_50pc_1p25perc_2mm_Capill_100ms_13m
NOH_50pc_1p25perc_2mm_Capill_100ms_13m
NOH_50pc_1p25perc_2mm_Capill_100ms_13m
NOH_50pc_1p25perc_2mm_Capill_100ms_1p1m
NOH_50pc_1p25perc_2mm_Capill_100ms_1p1m
NOH_50pc_1p25perc_2mm_Capill_100ms_1p1m
NOH_50pc_1p25perc_2mm_Capill_100ms_1p1m
NOH_50pc_1p25perc_2mm_Capill_100ms_1p1m
NOH_50pc_1p25perc_2mm_Capill_100ms_1p1m
NOH_50pc_1p25perc_Capill_2mm_50ms_13m
NOH_50pc_1p25perc_Capill_2mm_50ms_13m
NOH_50pc_1p25perc_Capill_2mm_50ms_13m
NOH_50pc_1p25perc_Capill_2mm_50ms_13m
NOH_50pc_1p25perc_Capill_2mm_50ms_13m
NOH_50pc_1p25perc_Capill_2mm_50ms_13m
NOH_50pc_1p25perc_Capill_2mm_50ms_1p1m
NOH_50pc_1p25perc_Capill_2mm_50ms_1p1m
NOH_50pc_1p25perc_Capill_2mm_50ms_1p1m
NOH_50pc_1p25perc_Capill_2mm_50ms_1p1m
NOH_50pc_1p25perc_Capill_2mm_50ms_1p1m
NOH_50pc_1p25perc_Capill_2mm_50ms_1p1m
NOH_50pc_2p5perc_2mm_Capill_100ms_13m
NOH_50pc_2p5perc_2mm_Capill_100ms_13m
NOH_50pc_2p5perc_2mm_Capill_100ms_13m
NOH_50pc_2p5perc_2mm_Capill_100ms_13m
NOH_50pc_2p5perc_2mm_Capill_100ms_13m
NOH_50pc_2p5perc_2mm_Capill_100ms_13m
NOH_50pc_2p5perc_2mm_Capill_100ms_1p1m
NOH_50pc_2p5perc_2mm_Capill_100ms_1p1m
NOH_50pc_2p5perc_2mm_Capill_100ms_1p1m
NOH_50pc_2p5perc_2mm_Capill_100ms_1p1m
NOH_50pc_2p5perc_2mm_Capill_100ms_1p1m
NOH_50pc_2p5perc_2mm_Capill_100ms_1p1m
NOH_50pc_2p5perc_Capill_2mm_50ms_13m
NOH_50pc_2p5perc_Capill_2mm_50ms_13m
NOH_50pc_2p5perc_Capill_2mm_50ms_13m
NOH_50pc_2p5perc_Capill_2mm_50ms_13m
NOH_50pc_2p5perc_Capill_2mm_50ms_13m
NOH_50pc_2p5perc_Capill_2mm_50ms_13m
NOH_50pc_2p5perc_Capill_2mm_50ms_1p1m
NOH_50pc_2p5perc_Capill_2mm_50ms_1p1m
NOH_50pc_2p5perc_Capill_2mm_50ms_1p1m
NOH_50pc_2p5perc_Capill_2mm_50ms_1p1m
NOH_50pc_2p5perc_Capill_2mm_50ms_1p1m
NOH_50pc_2p5perc_Capill_2mm_50ms_1p1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_100ms_1_1m
NOH_NG_2_Melt_20ms_1_1m
NOH_NG_2_Melt_20ms_1_1m
NOH_NG_2_Melt_20ms_1_1m
NOH_NG_2_Melt_20ms_1_1m
NOH_NG_2_Melt_20ms_1_1m
NOH_NG_2_Melt_20ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_100ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_2_elastomer_20ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_100ms_1_1m
NOH_NG_4_Melt_20ms_1_1m
NOH_NG_4_Melt_20ms_1_1m
NOH_NG_4_Melt_20ms_1_1m
NOH_NG_4_Melt_20ms_1_1m
NOH_NG_4_Melt_20ms_1_1m
NOH_NG_4_Melt_20ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_100ms_1_1m
NOH_NG_4_elastomer_20ms_1_1m
NOH_NG_4_elastomer_20ms_1_1m
NOH_NG_4_elastomer_20ms_1_1m
NOH_NG_4_elastomer_20ms_1_1m
NOH_NG_4_elastomer_20ms_1_1m
NOH_NG_4_elastomer_20ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m
NOH_NG_6_Melt_100ms_1_1m